server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/usuarios/**
          filters:
            - StripPrefix=1

        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hoteles/**
          filters:
            - StripPrefix=1

        - id: calificacion-service
          uri: lb://CALIFICACION-SERVICE
          predicates:
            - Path=/calificaciones/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
